### ISSUE TITLE
Battery status for thermostate

### ISSUE THREAD

**Issue by 1192410** [peribeir/homeassistant-rademacher#42]
Hi Pedro, 

question for you: Would it be possible to add the battery status to the thermostate ? the device call is as follow: 

{"response":"get_device","device":{"description":"Heizkörper Esszimmer","deviceGroup":5,"did":87,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset28"},"messages":[],"name":"Heizkörper Esszimmer","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":190,"acttemperatur":189},"visible":true,"deviceNumber":"35003064","uid":"e135ad_1","voiceControlledBy":"Alexa,Google","origin":"HomePilot","batteryStatus":100,"batteryLow":false,"posMin":40,"posMax":280,"sceneConfig":["DIRECT_FUNCTION_CMD","TARGET_TEMPERATURE_CFG","AUTO_MODE_CFG"]}}

Many thanks, Andreas

**Comment by peribeir** [comment]
Hi Andreas
I just added the battery level entity for thermostats, when reported.
Can you check if v1.8.0 works for you?
Br,
Pedro

**Comment by 1192410** [comment]
Hi Pedro, 

I have installed the latest version. It's not showing up. I have installed the latest version. 



![image](https://user-images.githubusercontent.com/73297737/161526744-968102d1-a689-497e-8441-c5a3a5fa683e.png)
![image](https://user-images.githubusercontent.com/73297737/161526886-1815a0b2-2681-4a17-b2f7-6ff090146b90.png)

**Comment by 1192410** [comment]
{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"TEMPERATURE_INT_CFG","value":"18.14","read_only":false,"timestamp":1649089295},{"name":"EXT_OPEN_WINDOW_DETECT_EVT","value":"false","read_only":true,"timestamp":1649089295},{"name":"VERSION_CFG","value":"1.2-1","read_only":false,"timestamp":1649089295},{"name":"BATT_VALUE_EVT","value":"100","read_only":true,"timestamp":1649089295},{"name":"PROD_CODE_DEVICE_LOC","value":"35003064","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1649089295},{"name":"CONTACT_OPEN_CMD","read_only":false,"timestamp":1603442049},{"name":"NAME_DEVICE_LOC","value":"Heizkörper Esszimmer","read_only":false,"timestamp":-1},{"name":"PROT_ID_DEVICE_LOC","value":"e135ad_1","read_only":false,"timestamp":-1},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_LOC","value":"iconset28","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"5","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"VOICE_CONTROLLED_LOC","value":"Alexa,Google","read_only":false,"timestamp":-1},{"name":"AUTO_MODE_CFG","value":"true","read_only":false,"timestamp":1649089295},{"name":"TARGET_TEMPERATURE_CFG","value":"19.0","min_value":"4.0","max_value":"28.0","step_size":"0.5","read_only":false,"timestamp":1649089295},{"name":"BATT_LOW_EVT","value":"false","read_only":true,"timestamp":1649089295},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"87","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"e135ad","read_only":false,"timestamp":-1},{"name":"CONTACT_CLOSE_CMD","read_only":false,"timestamp":1603442054},{"name":"BOOST_ACTIVE_CFG","value":"false","read_only":false,"timestamp":1649089295},{"name":"CONTACT_AUTO_CFG","value":"false","read_only":false,"timestamp":1648999325},{"name":"INT_OPEN_WINDOW_DETECT_EVT","value":"false","read_only":true,"timestamp":1649089295},{"name":"BATT_LOW_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"BOOST_TIME_CFG","value":"15","min_value":"4","max_value":"60","step_size":"1","read_only":false,"timestamp":1649089295},{"name":"WAKE_UP_TIME_CFG","value":"15","min_value":"2","max_value":"60","step_size":"1","read_only":false,"timestamp":1649089295},{"name":"BATT_EMPTY_POS_CFG","value":"0","min_value":"0","max_value":"7","step_size":"1","read_only":false,"timestamp":1648999028},{"name":"BATT_LOW_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Heizkörper Esszimmer","read_only":false,"timestamp":-1},{"name":"TIME_AUTO_CFG","value":"true","read_only":false,"timestamp":1649089295}],"scenes":[]}}}

**Comment by peribeir** [comment]
Ok, seems capabilities are different for thermostats.
v1.8.1 should fix it.

**Comment by 1192410** [comment]
Hi Pedro, 

Many thanks. I really appreciate your help, unfortunately still not showing up with the your latest release. It's not an urgent matter, but if I can help you with some more details, more than happy to. 

Best, Andreas

**Comment by peribeir** [comment]
Hi Andreas,
I'm afraid I cannot find the reason for you not having the battery level entity detected.
Can you check HA logs if there are any errors?
Also, please try to do reload of the integration, maybe there was something wrong when loading.
Br,
Pedro

**Comment by 1192410** [comment]
Hi Pedro, nothing in the logs when I search for Rademacher or Error that seems to be connected to that. I think we leave it a kind of mystery and close it. 

![image](https://user-images.githubusercontent.com/73297737/162140314-9b8874e1-c201-4abe-8c04-2394f88d1193.png)
